version: 0.0
os: linux
artifacts:
  files:
    - source: /
      destination: /usr/share/nginx/html/
      overwrite: true
file_exists_behavior: OVERWRITE
hooks:
BeforeInstall:
- location: scripts/install_dependencies.sh
timeout: 20
runas: root
- location: scripts/start_server.sh
timeout: 20
runas: root
ApplicationStop:
- location: scripts/stop_server.sh
timeout: 20
runas: root