version: 0.0
os: linux
files:
- source: /Users/Guruu/Desktop/AWS-Projectsv2/Project6_CI-CD
destination: /home/ec2-user/nginx-instance
hooks:
BeforeInstall:
- location: scripts/install_dependencies.sh
timeout: 300
runas: ec2-user
- location: scripts/start_server.sh
timeout: 300
runas: ec2-user
ApplicationStop:
- location: scripts/stop_server.sh
timeout: 300
runas: ec2-user