version: 0.0
os: linux
artifacts:
  files:
    - appspec.yml
    - install_dependencies.sh
    - start_server.sh
    - stop_server.sh
files:
- source: /
destination: /usr/share/nginx/html/
hooks:
BeforeInstall:
- location: scripts/install_dependencies.sh
timeout: 300
runas: root
- location: scripts/start_server.sh
timeout: 300
runas: root
ApplicationStop:
- location: scripts/stop_server.sh
timeout: 300
runas: root